#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PAYLOAD=$(mktemp /tmp/resource-in.XXXXXX)

cat > "$PAYLOAD" <&0

TS=$(jq '.version.timestamp // empty' < "$PAYLOAD")
REF=$(jq '.version.ref // empty' < "$PAYLOAD")
[ -z "$TS" ] && TS='"none"'
[ -z "$REF" ] && REF='"none"'

jq -n "{
  version: {
    timestamp: $TS,
    ref: $REF
  }
}" >&3
